import type { RequirementLayer } from "../end-points/extract/extractApi";

export const BRD_DEFAULTS: RequirementLayer = {
  scope: {
    in_scope: "",
    out_of_scope: "",
  },
  bsa_input: "",
  requirements: "",
  filters_and_parameters: {
    company: "",
    business: "",
    state: "",
    line_of_business: "",
    financial_arrangement: "",
    product_plan_type: "",
    extended_product: "",
    coverage_plan: "",
    customer_id: "",
    group_id: "",
    claim_status: "",
    blue_card_indicator: "",
    excluded_companies: "",
    excluded_lob: "",
    sensitive_data_exclusion: "",
    opt_out_groups: "",
    date_parameters: {
      member_active_enrollment: "",
      active_plan_group: "",
      start_date: "",
      history_lookback: "",
      rollover_period: "",
      claim_service_dates: "",
      claim_posted_dates: "",
      paid_dates: "",
      pharmacy_fill_dates: "",
      pharmacy_cut_dates: "",
    },
  },
  file_attributes_mapping: {
    file_count: "",
    subject_areas: "",
    file_frequency: "",
    file_type: "",
    file_delimiter: "Pipe (|)",
    file_naming_convention: "",
    file_compression: "",
    file_encryption: "",
    control_file_required: "",
    file_delivery_method: "",
    field_headers: "",
    trailer_required: "",
    field_requirements: "",
    default_values: "",
    data_format_rules: "",
  },
  file_specs: {
    physical_file_name: "",
    vendor_name: "",
    transfer_method: "IFG",
    vendor_contact_name: "",
    frequency_mode: "",
    vendor_phone_number: "",
    dependencies: "",
    vendor_email: "",
    email_notification_dl: "",
    file_delimiter: "Pipe (|)",
    file_extension: ".txt",
    date_timestamp_format: "YYYYMMDDHHMMSS",
    header_record_number: "Field Count in the file",
    trailer_record_number: "0",
    quote_indicator: "",
    file_population_type: "",
    file_compression_type: "",
    receive_files_when_no_data: "",
    assumptions: "",
    vendor_server_name: "",
    vendor_file_drop_location: "",
    control_file_name: "",
    control_file_delimiter: "Pipe (|)",
    control_file_extension: ".ctl",
    control_file_header_present: "",
    control_record_number: "",
    control_file_amount_column_count: "",
    done_file_present: "Not Applicable",
    file_arrival_schedule: "",
    estimated_record_count_initial: "",
    estimated_record_count_ongoing: "",
  },
  common_rules: {
    interface_code: "",
    history_required: "",
    effective_dates_from: "",
    effective_dates_to: "",
    posted_dates_from: "",
    posted_dates_to: "",
    rolling_month_requirement: "",
    driver_required: "",
    incremental_history_required: "",
    runout_required: "",
    number_of_months: "",
    sensitive_category_list: "",
    deidentity_extract: "",
    comments: "",
    last_updated_date: "",
  },
};
