export const valuesData = [
  {
    "Transfer Method": "Pull",
    "Frequency Mode": "Daily",
    "File Delimiter": "Pipe (|)",
    "File Extension": ".txt",
    "Date Timestamp Format": "YYYYMMDD",
    "File Population Type": "Full",
    "File Type": "Incoming",
    "File Compression Type": "ZIP",
    "Control File Delimiter": "Pipe (|)",
    "Control File Extension": ".ctl",
    "Data Type": "Binary",
    "Recieve Files When No Data(Empty Files)": "Yes",
    "Control File Header Present": "Yes",
    ".done File Present": "Yes",
    "Quote Indicator": "No"
  },
  {
    "Transfer Method": "Push",
    "Frequency Mode": "Weekly",
    "File Delimiter": "Comma (,)",
    "File Extension": ".csv",
    "Date Timestamp Format": "YYYYMMDD_HHMISS",
    "File Population Type": "Incremental",
    "File Type": "Outgoing",
    "File Compression Type": "GZIP",
    "Control File Delimiter": "Comma (,)",
    "Control File Extension": ".txt",
    "Data Type": "boolean",
    "Recieve Files When No Data(Empty Files)": "No",
    "Control File Header Present": "No",
    ".done File Present": "No",
    "Quote Indicator": "Yes"
  },
  {
    "Transfer Method": "IFG",
    "Frequency Mode": "Monthly",
    "File Delimiter": "Tab",
    "File Extension": ".dat",
    "Date Timestamp Format": "YYYYMMDDHHMISS",
    "File Population Type": "Not Applicable",
    "File Type": "Not Applicable",
    "File Compression Type": "Not Applicable",
    "Control File Delimiter": "Tab",
    "Control File Extension": ".control",
    "Data Type": "Byteint",
    "Recieve Files When No Data(Empty Files)": "Not Applicable",
    "Control File Header Present": "Not Applicable",
    ".done File Present": "Not Applicable",
    "Quote Indicator": "Not Applicable"
  },
  {
    "Transfer Method": "Direct SFTP",
    "Frequency Mode": "Yearly",
    "File Delimiter": "Fixed",
    "File Extension": ".data",
    "Date Timestamp Format": "YYYYMM",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": "Fixed",
    "Control File Extension": "Not Applicable",
    "Data Type": "Char",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": "Direct FTP",
    "Frequency Mode": "Bi-Weekly",
    "File Delimiter": "Tilde (~)",
    "File Extension": ".gpg",
    "Date Timestamp Format": "MMDDYYYY",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": "Tilde (~)",
    "Control File Extension": null,
    "Data Type": "Date",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": "Email",
    "Frequency Mode": "Bi-Monthly",
    "File Delimiter": "Cedilla",
    "File Extension": ".json",
    "Date Timestamp Format": "MMDDYYYY_HHMISS",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": "Cedilla",
    "Control File Extension": null,
    "Data Type": "Datetime",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": "STTM Drop",
    "Frequency Mode": "Quarterly",
    "File Delimiter": "Not Applicable",
    "File Extension": ".optout",
    "Date Timestamp Format": "DDMMYYYY_HHMMSS",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": "Not Applicable",
    "Control File Extension": null,
    "Data Type": "Decimal",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": "Business Drop",
    "Frequency Mode": "Half Yearly",
    "File Delimiter": null,
    "File Extension": ".pdf",
    "Date Timestamp Format": "DDMMYYYY",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Float",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": "Not Applicable",
    "Frequency Mode": "On-Demand",
    "File Delimiter": null,
    "File Extension": ".pgp",
    "Date Timestamp Format": "YYYY_MM_DD",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Integer",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": "One-Time",
    "File Delimiter": null,
    "File Extension": ".tsv",
    "Date Timestamp Format": "MMYYYY",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Long",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": "Other",
    "File Delimiter": null,
    "File Extension": ".xls",
    "Date Timestamp Format": "YYYY_YYYYMMDD_HHMMSS",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Nvarchar",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": "Not Applicable",
    "File Delimiter": null,
    "File Extension": ".xlsx",
    "Date Timestamp Format": "Not Applicable",
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Smallint",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": null,
    "File Delimiter": null,
    "File Extension": ".xml",
    "Date Timestamp Format": null,
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "String",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": null,
    "File Delimiter": null,
    "File Extension": ".CSV",
    "Date Timestamp Format": null,
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Time",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": null,
    "File Delimiter": null,
    "File Extension": ".TXT",
    "Date Timestamp Format": null,
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Timestamp",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": null,
    "File Delimiter": null,
    "File Extension": "Not Applicable",
    "Date Timestamp Format": null,
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Varchar",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": null,
    "File Delimiter": null,
    "File Extension": null,
    "Date Timestamp Format": null,
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Varchar (Max)",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  },
  {
    "Transfer Method": null,
    "Frequency Mode": null,
    "File Delimiter": null,
    "File Extension": null,
    "Date Timestamp Format": null,
    "File Population Type": null,
    "File Type": null,
    "File Compression Type": null,
    "Control File Delimiter": null,
    "Control File Extension": null,
    "Data Type": "Varchar(Max)",
    "Recieve Files When No Data(Empty Files)": null,
    "Control File Header Present": null,
    ".done File Present": null,
    "Quote Indicator": null
  }
]
