from typing import Any

response_schema = {
    "type": "object",
    "properties": {

        "scope": {
            "type": "object",
            "properties": {
                "in_scope": {"type": "string"},
                "out_of_scope": {"type": "string"}
            },
            "required": ["in_scope", "out_of_scope"]
        },

        "bsa_input": {"type": "string"},

        "requirements": {"type": "string"},

        "filters_and_parameters": {
            "type": "object",
            "properties": {
                "company": {"type": "string"},
                "business": {"type": "string"},
                "state": {"type": "string"},
                "line_of_business": {"type": "string"},
                "financial_arrangement": {"type": "string"},
                "product_plan_type": {"type": "string"},
                "extended_product": {"type": "string"},
                "coverage_plan": {"type": "string"},
                "customer_id": {"type": "string"},
                "group_id": {"type": "string"},
                "claim_status": {"type": "string"},
                "blue_card_indicator": {"type": "string"},
                "excluded_companies": {"type": "string"},
                "excluded_lob": {"type": "string"},
                "sensitive_data_exclusion": {"type": "string"},
                "opt_out_groups": {"type": "string"},

                "date_parameters": {
                    "type": "object",
                    "properties": {
                        "member_active_enrollment": {"type": "string"},
                        "active_plan_group": {"type": "string"},
                        "start_date": {"type": "string"},
                        "history_lookback": {"type": "string"},
                        "rollover_period": {"type": "string"},
                        "claim_service_dates": {"type": "string"},
                        "claim_posted_dates": {"type": "string"},
                        "paid_dates": {"type": "string"},
                        "pharmacy_fill_dates": {"type": "string"},
                        "pharmacy_cut_dates": {"type": "string"}
                    },
                    "required": [
                        "member_active_enrollment",
                        "active_plan_group",
                        "start_date",
                        "history_lookback",
                        "rollover_period",
                        "claim_service_dates",
                        "claim_posted_dates",
                        "paid_dates",
                        "pharmacy_fill_dates",
                        "pharmacy_cut_dates"
                    ]
                }
            },
            "required": [
                "company",
                "business",
                "state",
                "line_of_business",
                "financial_arrangement",
                "product_plan_type",
                "extended_product",
                "coverage_plan",
                "customer_id",
                "group_id",
                "claim_status",
                "blue_card_indicator",
                "excluded_companies",
                "excluded_lob",
                "sensitive_data_exclusion",
                "opt_out_groups",
                "date_parameters"
            ]
        },

        "file_attributes_mapping": {
            "type": "object",
            "properties": {
                "file_count": {"type": "string"},
                "subject_areas": {"type": "string"},
                "file_frequency": {"type": "string"},
                "file_type": {"type": "string"},
                "file_delimiter": {"type": "string"},
                "file_naming_convention": {"type": "string"},
                "file_compression": {"type": "string"},
                "file_encryption": {"type": "string"},
                "control_file_required": {"type": "string"},
                "file_delivery_method": {"type": "string"},
                "field_headers": {"type": "string"},
                "trailer_required": {"type": "string"},
                "field_requirements": {"type": "string"},
                "default_values": {"type": "string"},
                "data_format_rules": {"type": "string"}
            },
            "required": [
                "file_count",
                "subject_areas",
                "file_frequency",
                "file_type",
                "file_delimiter",
                "file_naming_convention",
                "file_compression",
                "file_encryption",
                "control_file_required",
                "file_delivery_method",
                "field_headers",
                "trailer_required",
                "field_requirements",
                "default_values",
                "data_format_rules"
            ]
        },

        # EXISTING — FILE SPECS (FULLY EXPANDED)
        "file_specs": {
            "type": "object",
            "properties": {
                "physical_file_name": {"type": "string"},
                "vendor_name": {"type": "string"},
                "transfer_method": {"type": "string"},
                "vendor_contact_name": {"type": "string"},
                "frequency_mode": {"type": "string"},
                "vendor_phone_number": {"type": "string"},
                "dependencies": {"type": "string"},
                "vendor_email": {"type": "string"},
                "email_notification_dl": {"type": "string"},
                "file_delimiter": {"type": "string"},
                "file_extension": {"type": "string"},
                "date_timestamp_format": {"type": "string"},
                "header_record_number": {"type": "string"},
                "trailer_record_number": {"type": "string"},
                "quote_indicator": {"type": "string"},
                "file_population_type": {"type": "string"},
                "file_compression_type": {"type": "string"},
                "receive_files_when_no_data": {"type": "string"},
                "assumptions": {"type": "string"},
                "vendor_server_name": {"type": "string"},
                "vendor_file_drop_location": {"type": "string"},
                "control_file_name": {"type": "string"},
                "control_file_delimiter": {"type": "string"},
                "control_file_extension": {"type": "string"},
                "control_file_header_present": {"type": "string"},
                "control_record_number": {"type": "string"},
                "control_file_amount_column_count": {"type": "string"},
                "done_file_present": {"type": "string"},
                "file_arrival_schedule": {"type": "string"},
                "estimated_record_count_initial": {"type": "string"},
                "estimated_record_count_ongoing": {"type": "string"}
            },
            "required": [
                "physical_file_name",
                "vendor_name",
                "transfer_method",
                "vendor_contact_name",
                "frequency_mode",
                "vendor_phone_number",
                "dependencies",
                "vendor_email",
                "email_notification_dl",
                "file_delimiter",
                "file_extension",
                "date_timestamp_format",
                "header_record_number",
                "trailer_record_number",
                "quote_indicator",
                "file_population_type",
                "file_compression_type",
                "receive_files_when_no_data",
                "assumptions",
                "vendor_server_name",
                "vendor_file_drop_location",
                "control_file_name",
                "control_file_delimiter",
                "control_file_extension",
                "control_file_header_present",
                "control_record_number",
                "control_file_amount_column_count",
                "done_file_present",
                "file_arrival_schedule",
                "estimated_record_count_initial",
                "estimated_record_count_ongoing"
            ]
        },

        # EXISTING — COMMON RULES
        "common_rules": {
            "type": "object",
            "properties": {
                "interface_code": {"type": "string"},
                "history_required": {"type": "string"},
                "effective_dates_from": {"type": "string"},
                "effective_dates_to": {"type": "string"},
                "posted_dates_from": {"type": "string"},
                "posted_dates_to": {"type": "string"},
                "rolling_month_requirement": {"type": "string"},
                "driver_required": {"type": "string"},
                "incremental_history_required": {"type": "string"},
                "runout_required": {"type": "string"},
                "number_of_months": {"type": "string"},
                "sensitive_category_list": {"type": "string"},
                "deidentity_extract": {"type": "string"},
                "comments": {"type": "string"},
                "last_updated_date": {"type": "string"}
            },
            "required": [
                "interface_code",
                "history_required",
                "effective_dates_from",
                "effective_dates_to",
                "posted_dates_from",
                "posted_dates_to",
                "rolling_month_requirement",
                "driver_required",
                "incremental_history_required",
                "runout_required",
                "number_of_months",
                "sensitive_category_list",
                "deidentity_extract",
                "comments",
                "last_updated_date"
            ]
        }
    },

    "required": [
        "scope",
        "bsa_input",
        "requirements",
        "filters_and_parameters",
        "file_attributes_mapping",
        "file_specs",
        "common_rules"
    ]
}

def _build_empty_requirement_schema() -> dict[str, Any]:
    return {
        "scope": {"in_scope": "", "out_of_scope": ""},
        "bsa_input": "",
        "requirements": "",

        "filters_and_parameters": {
            "company": "",
            "business": "",
            "state": "",
            "line_of_business": "",
            "financial_arrangement": "",
            "product_plan_type": "",
            "extended_product": "",
            "coverage_plan": "",
            "customer_id": "",
            "group_id": "",
            "claim_status": "",
            "blue_card_indicator": "",
            "excluded_companies": "",
            "excluded_lob": "",
            "sensitive_data_exclusion": "",
            "opt_out_groups": "",
            "date_parameters": {
                "member_active_enrollment": "",
                "active_plan_group": "",
                "start_date": "",
                "history_lookback": "",
                "rollover_period": "",
                "claim_service_dates": "",
                "claim_posted_dates": "",
                "paid_dates": "",
                "pharmacy_fill_dates": "",
                "pharmacy_cut_dates": ""
            }
        },

        "file_attributes_mapping": {
            "file_count": "",
            "subject_areas": "",
            "file_frequency": "",
            "file_type": "",
            "file_delimiter": "",
            "file_naming_convention": "",
            "file_compression": "",
            "file_encryption": "",
            "control_file_required": "",
            "file_delivery_method": "",
            "field_headers": "",
            "trailer_required": "",
            "field_requirements": "",
            "default_values": "",
            "data_format_rules": ""
        },

         "file_specs": {
            "physical_file_name": "",
            "vendor_name": "",
            "transfer_method": "",
            "vendor_contact_name": "",
            "frequency_mode": "",
            "vendor_phone_number": "",
            "dependencies": "",
            "vendor_email": "",
            "email_notification_dl": "",
            "file_delimiter": "",
            "file_extension": "",
            "date_timestamp_format": "",
            "header_record_number": "",
            "trailer_record_number": "",
            "quote_indicator": "",
            "file_population_type": "",
            "file_compression_type": "",
            "receive_files_when_no_data": "",
            "assumptions": "",
            "vendor_server_name": "",
            "vendor_file_drop_location": "",
            "control_file_name": "",
            "control_file_delimiter": "",
            "control_file_extension": "",
            "control_file_header_present": "",
            "control_record_number": "",
            "control_file_amount_column_count": "",
            "done_file_present": "",
            "file_arrival_schedule": "",
            "estimated_record_count_initial": "",
            "estimated_record_count_ongoing": "",
        },
        "common_rules": {
            "interface_code": "",
            "history_required": "",
            "effective_dates_from": "",
            "effective_dates_to": "",
            "posted_dates_from": "",
            "posted_dates_to": "",
            "rolling_month_requirement": "",
            "driver_required": "",
            "incremental_history_required": "",
            "runout_required": "",
            "number_of_months": "",
            "sensitive_category_list": "",
            "deidentity_extract": "",
            "comments": "",
            "last_updated_date": "",
        },
    }
