export const TOOLTIP_CONTENT = {
  dataDictionary: "Upload a data dictionary file (.csv, .xlsx, .txt, .docx) that describes the data fields.",
  brdFile: "Upload the Business Requirements Document (BRD) for this project.",
  projectName: "Enter the name of the project.",
  deliveryFrequency: "Specify how often files will be delivered (e.g., daily, weekly, monthly).",
  vendorName: "Enter the name of the vendor providing the data.",
  contactPersonEmail: "Enter the email address of the primary contact person.",
  contactName: "Enter the full name of the primary contact person.",
  phoneNumber: "Enter the contact person's phone number.",
  serverName: "Enter the server name or hostname used for file transfer.",
  transferMethod: "Select the method used to transfer files (e.g., SFTP, FTPS, API).",
  frequencyMode: "Select the frequency mode for file delivery.",
  compressionType: "Select the compression format used for the files (e.g., ZIP, GZIP, None).",
  populationType: "Select the population type for the file (e.g., Full, Incremental).",
  headerRecordNumber: "Enter the number of header records in the file.",
  trailerRecordNumber: "Enter the number of trailer records in the file.",
  quoteIndicator: "Specify the quote character used in the file (e.g., double quote, single quote, none).",
  dateTimestampFormat: "Specify the date/timestamp format used in the file (e.g., YYYY-MM-DD).",
  emailNotificationDl: "Enter the email distribution list for file delivery notifications.",
  receiveFileWhenNoData: "Indicate whether a file should be received even when there is no data.",
  assumptions: "List any assumptions made for this data feed.",
  dependencies: "List any dependencies or prerequisites for this data feed.",
};
