"""Element names for 837-related X12 segments (005010 companion guide / ASC X12)."""

from __future__ import annotations

# Segment ID → HIPAA / X12 segment name
SEGMENT_NAMES: dict[str, str] = {
    "ISA": "Interchange Control Header",
    "IEA": "Interchange Control Trailer",
    "GS": "Functional Group Header",
    "GE": "Functional Group Trailer",
    "ST": "Transaction Set Header",
    "SE": "Transaction Set Trailer",
    "BHT": "Beginning of Hierarchical Transaction",
    "NM1": "Individual or Organizational Name",
    "PER": "Administrative Communications Contact",
    "HL": "Hierarchical Level",
    "PRV": "Provider Information",
    "N3": "Party Location",
    "N4": "Geographic Location",
    "REF": "Reference Information",
    "SBR": "Subscriber Information",
    "PAT": "Patient Information",
    "DMG": "Demographic Information",
    "CLM": "Claim Information",
    "DTP": "Date or Time or Period",
    "PWK": "Paperwork",
    "AMT": "Monetary Amount Information",
    "HI": "Health Care Diagnosis Code",
    "LX": "Service Line Number",
    "SV1": "Professional Service",
    "SV2": "Institutional Service Line",
    "SV3": "Dental Service",
    "SV5": "Durable Medical Equipment Service",
    "SVD": "Service Line Adjudication Information",
    "CR1": "Ambulance Transport Information",
    "CR2": "Spinal Manipulation Service Information",
    "CR3": "Durable Medical Equipment Certification",
    "CRC": "Conditions Indicator",
    "CTP": "Pricing Information",
    "DN1": "Orthodontic Information",
    "DN2": "Tooth Status",
    "FRM": "Supporting Documentation",
    "HCP": "Line Pricing/Repricing Information",
    "K3": "File Information",
    "LIN": "Item Identification",
    "LQ": "Industry Code Identification",
    "MEA": "Measurements",
    "MIA": "Inpatient Adjudication Information",
    "MOA": "Outpatient Adjudication Information",
    "NTE": "Note/Special Instruction",
    "OI": "Other Insurance Coverage Information",
    "PS1": "Purchased Service Information",
    "QTY": "Quantity Information",
    "TOO": "Tooth Identification",
    "CL1": "Institutional Claim Code",
    "CAS": "Claims Adjustment",
}

# Segment ID → list of (element_name, optional code_set_id for whole element value)
# Index i corresponds to element i+1 (first data element after segment ID).
ELEMENT_DEFS: dict[str, list[tuple[str, str | None]]] = {
    "ISA": [
        ("Authorization Information Qualifier", "ISA01"),
        ("Authorization Information", None),
        ("Security Information Qualifier", "ISA03"),
        ("Security Information", None),
        ("Interchange ID Qualifier (Sender)", "ISA05"),
        ("Interchange Sender ID", None),
        ("Interchange ID Qualifier (Receiver)", "ISA07"),
        ("Interchange Receiver ID", None),
        ("Interchange Date", None),
        ("Interchange Time", None),
        ("Repetition Separator", None),
        ("Interchange Control Version Number", None),
        ("Interchange Control Number", None),
        ("Acknowledgment Requested", "ISA14"),
        ("Usage Indicator", "ISA15"),
        ("Component Element Separator", None),
    ],
    "IEA": [
        ("Number of Included Functional Groups", None),
        ("Interchange Control Number", None),
    ],
    "GS": [
        ("Functional Identifier Code", "GS01"),
        ("Application Sender's Code", None),
        ("Application Receiver's Code", None),
        ("Date", None),
        ("Time", None),
        ("Group Control Number", None),
        ("Responsible Agency Code", None),
        ("Version / Release / Industry Identifier Code", "GS08"),
    ],
    "GE": [
        ("Number of Transaction Sets Included", None),
        ("Group Control Number", None),
    ],
    "ST": [
        ("Transaction Set Identifier Code", None),
        ("Transaction Set Control Number", None),
        ("Implementation Convention Reference", "GS08"),
    ],
    "SE": [
        ("Number of Included Segments", None),
        ("Transaction Set Control Number", None),
    ],
    "BHT": [
        ("Hierarchical Structure Code", None),
        ("Transaction Set Purpose Code", "BHT02"),
        ("Reference Identification", None),
        ("Date", None),
        ("Time", None),
        ("Transaction Type Code", "BHT06"),
    ],
    "NM1": [
        ("Entity Identifier Code", "NM101"),
        ("Entity Type Qualifier", "NM102"),
        ("Name Last or Organization Name", None),
        ("Name First", None),
        ("Name Middle", None),
        ("Name Prefix", None),
        ("Name Suffix", None),
        ("Identification Code Qualifier", "NM108"),
        ("Identification Code", None),
    ],
    "PER": [
        ("Contact Function Code", "PER01"),
        ("Name", None),
        ("Communication Number Qualifier", "PER03"),
        ("Communication Number", None),
        ("Communication Number Qualifier", "PER05"),
        ("Communication Number", None),
    ],
    "HL": [
        ("Hierarchical ID Number", None),
        ("Hierarchical Parent ID Number", None),
        ("Hierarchical Level Code", "HL03"),
        ("Hierarchical Child Code", "HL04"),
    ],
    "PRV": [
        ("Provider Code", "PRV01"),
        ("Reference Identification Qualifier", "PRV02"),
        ("Reference Identification", None),
    ],
    "N3": [
        ("Address Information", None),
        ("Address Information", None),
    ],
    "N4": [
        ("City Name", None),
        ("State or Province Code", None),
        ("Postal Code", None),
        ("Country Code", None),
    ],
    "REF": [
        ("Reference Identification Qualifier", "REF01"),
        ("Reference Identification", None),
        ("Description", None),
    ],
    "SBR": [
        ("Payer Responsibility Sequence Number Code", "SBR01"),
        ("Individual Relationship Code", None),
        ("Reference Identification", None),
        ("Name", None),
        ("Insurance Type Code", None),
        ("Coordination of Benefits Code", None),
        ("Yes/No Condition or Response Code", None),
        ("Employment Status Code", None),
        ("Claim Filing Indicator Code", "SBR09"),
    ],
    "PAT": [
        ("Individual Relationship Code", "PAT01"),
        ("Patient Location Code", None),
        ("Employment Status Code", None),
        ("Date Time Period Format Qualifier", "DMG01"),
        ("Date Time Period", None),
        ("Unit or Basis for Measurement Code", None),
        ("Weight", None),
        ("Yes/No Condition or Response Code", None),
    ],
    "DMG": [
        ("Date Time Period Format Qualifier", "DMG01"),
        ("Date Time Period", None),
        ("Gender Code", "DMG03"),
    ],
    "CLM": [
        ("Patient Control Number", None),
        ("Total Claim Charge Amount", None),
        ("Claim Filing Indicator Code", None),
        ("Non-Institutional Claim Type Code", None),
        ("Health Care Service Location Information", "CLM05_POS"),
        ("Provider or Supplier Signature Indicator", "CLM06"),
        ("Assignment or Plan Participation Code", "CLM07"),
        ("Benefits Assignment Certification Indicator", "CLM06"),
        ("Release of Information Code", "CLM06"),
        ("Patient Signature Source Code", None),
        ("Related Causes Information", None),
        ("Special Program Indicator", None),
        ("Yes/No Condition or Response Code", None),
        ("Level of Service Code", None),
        ("Yes/No Condition or Response Code", None),
        ("Provider Agreement Code", None),
        ("Claim Submitter's Identifier", None),
        ("Delay Reason Code", None),
    ],
    "DTP": [
        ("Date/Time Qualifier", "DTP01"),
        ("Date Time Period Format Qualifier", "DTP02"),
        ("Date Time Period", None),
    ],
    "PWK": [
        ("Report Type Code", "PWK01"),
        ("Report Transmission Code", "PWK02"),
        ("Report Copies Needed", None),
        ("Entity Identifier Code", "NM101"),
        ("Identification Code Qualifier", "NM108"),
        ("Identification Code", None),
        ("Description", None),
    ],
    "AMT": [
        ("Amount Qualifier Code", "AMT01"),
        ("Monetary Amount", None),
    ],
    "HI": [
        ("Health Care Code Information", "HI01"),
    ],
    "LX": [
        ("Assigned Number", None),
    ],
    "SV1": [
        ("Composite Medical Procedure Identifier", "SV101"),
        ("Line Item Charge Amount", None),
        ("Unit or Basis for Measurement Code", None),
        ("Service Unit Count", None),
        ("Place of Service Code", None),
        ("Composite Diagnosis Code Pointer", None),
        ("Monetary Amount", None),
        ("Emergency Indicator", None),
        ("Multiple Procedure Code", None),
        ("Yes/No Condition or Response Code", None),
    ],
    "SV2": [
        ("Service Line Revenue Code", None),
        ("Composite Medical Procedure Identifier", "SV101"),
        ("Line Item Charge Amount", None),
        ("Unit or Basis for Measurement Code", None),
        ("Service Unit Count", None),
        ("Unit Rate", None),
        ("Non-Covered Charge Amount", None),
    ],
    "SV3": [
        ("Composite Medical Procedure Identifier", "SV101"),
        ("Monetary Amount", None),
        ("Facility Code Value", None),
        ("Oral Cavity Designation Code", None),
        ("Prosthesis Crown or Inlay Code", None),
        ("Procedure Count", None),
    ],
    "SV5": [
        ("Composite Medical Procedure Identifier", "SV101"),
        ("Unit or Basis for Measurement Code", None),
        ("Length of Medical Necessity", None),
        ("DMERC Rental Price", None),
        ("DMERC Purchase Price", None),
        ("Rental Unit Price Indicator", None),
    ],
    "SVD": [
        ("Reference Identification", None),
        ("Monetary Amount", None),
        ("Product/Service ID", None),
        ("Service Unit Count", None),
        ("Composite Medical Procedure Identifier", "SV101"),
    ],
    "CR1": [
        ("Unit or Basis for Measurement Code", None),
        ("Patient Weight", None),
        ("Ambulance Transport Code", None),
        ("Ambulance Transport Reason Code", None),
        ("Trip Purpose Description", None),
        ("Stretcher Purpose", None),
    ],
    "CR2": [
        ("Count", None),
        ("Quantity", None),
        ("Subluxation Level Code", None),
        ("Subluxation Level Code", None),
        ("Unit or Basis for Measurement Code", None),
        ("Quantity", None),
        ("Quantity", None),
        ("Nature of Condition Code", None),
        ("Yes/No Condition or Response Code", None),
        ("Condition Description", None),
    ],
    "CR3": [
        ("Certification Type Code", None),
        ("Unit or Basis for Measurement Code", None),
        ("Quantity", None),
        ("Yes/No Condition or Response Code", None),
        ("Condition Indicator", None),
    ],
    "CRC": [
        ("Code Category", "CRC01"),
        ("Condition Indicator", None),
    ],
    "OI": [
        ("Claim Filing Indicator Code", None),
        ("Claim Submission Reason Code", None),
        ("Yes/No Condition or Response Code", "OI03"),
        ("Patient Signature Source Code", None),
        ("Provider Agreement Code", None),
        ("Release of Information Code", None),
    ],
    "NTE": [
        ("Note Reference Code", None),
        ("Description", None),
    ],
    "CL1": [
        ("Admission Type Code", None),
        ("Admission Source Code", None),
        ("Patient Status Code", None),
    ],
    "CAS": [
        ("Claim Adjustment Group Code", None),
        ("Adjustment Reason Code", None),
        ("Monetary Amount", None),
        ("Quantity", None),
    ],
    "HCP": [
        ("Pricing Methodology", None),
        ("Monetary Amount", None),
        ("Monetary Amount", None),
        ("Product/Service ID", None),
        ("Unit or Basis for Measurement Code", None),
        ("Quantity", None),
        ("Reject Reason Code", None),
        ("Policy Compliance Code", None),
        ("Exception Code", None),
    ],
    "K3": [
        ("Fixed Format Information", None),
    ],
    "LIN": [
        ("Assigned Identification", None),
        ("Product/Service ID Qualifier", None),
        ("Product/Service ID", None),
    ],
    "LQ": [
        ("Code List Qualifier Code", None),
        ("Industry Code", None),
    ],
    "MEA": [
        ("Measurement Reference ID Code", None),
        ("Measurement Qualifier", None),
        ("Measurement Value", None),
    ],
    "MIA": [
        ("Quantity", None),
        ("Monetary Amount", None),
    ],
    "MOA": [
        ("Reimbursement Rate", None),
        ("HCPCS Payable Amount", None),
    ],
    "PS1": [
        ("Reference Identification", None),
        ("Monetary Amount", None),
    ],
    "QTY": [
        ("Quantity Qualifier", None),
        ("Quantity", None),
    ],
    "TOO": [
        ("Code List Qualifier Code", None),
        ("Tooth Number", None),
    ],
    "DN1": [
        ("Quantity", None),
        ("Monetary Amount", None),
    ],
    "DN2": [
        ("Reference Identification", None),
        ("Tooth Status Code", None),
    ],
    "FRM": [
        ("Assigned Identification", None),
        ("Yes/No Condition or Response Code", None),
    ],
    "CTP": [
        ("Class of Trade Code", None),
        ("Price Identifier Code", None),
        ("Unit Price", None),
        ("Quantity", None),
    ],
}
